### ISSUE TITLE
الفيوم - W مشكلة لا توجد بيانات

### ISSUE THREAD

**Issue by Mostafa-Abdallah** [mashhu/hand-held-16series#2]
@HassanAbdelzaher 

![Screen01](https://user-images.githubusercontent.com/30770255/75772491-bbf12300-5d54-11ea-926a-17d8312ce64f.jpg)

- hand_mh_st  لا يوجد به بيانات لنفس المسار فى

[مشكلة مجموعة 150.xlsx](https://github.com/mashhu/hand-held-16series/files/4281047/150.xlsx)

**Comment by HassanAbdelzaher** [comment]
دي مشكل المسارات الفارغة وتم حل المشكلة بعدم سحبها او تجهيوها

https://github.com/mashhu/hand-held-16series/releases/tag/17.99.23
