### ISSUE TITLE
مشاكل ماس اصدار 17.99.55 -2- الفيوم

### ISSUE THREAD

**Issue by Mostafa-Abdallah** [mashhu/hand-held-16series#4]
@HassanAbdelzaher 

![Untitled44](https://user-images.githubusercontent.com/30770255/95014056-9ad31680-0644-11eb-92bb-518e7b5eaca4.png)

**Comment by HassanAbdelzaher** [comment]
https://github.com/mashhu/hand-held-16series/releases/tag/17.99.57
